name = "kings-league-api"
main = "api/index.js"
compatibility_date = "2023-01-04"

[site]
bucket= "./assets"

[env.production]
vars={ENVIRONMENT="production"}
routes=[
    {pattern="api.kingsleague.bjvalmaseda.com", custom_domain=true}
] 