name: Check test for Pull Requests

on:
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
          run_install: false
      - name: Get pnpm directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STOTE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Testing
        run: pnpm test:cov
