name: Deploy API

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    if: github.ref_name=='main'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
          run_install: false
      - name: Get "pnpm" store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{runner.os}}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Execute Test
        run: npm run test:cov

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudflare Workers
    if: github.repository_owner == 'bjvalmaseda-dev'
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
          run_install: true
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api
          command: publish --env production
